version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka

  bitcoin-node:
    image: ruimarinho/bitcoin-core
    container_name: bitcoin-node
    ports:
      - "8332:8332"   # RPC port
      - "18332:18332" # Testnet RPC port
    environment:
      BITCOIN_NETWORK: testnet
      BITCOIN_RPCUSER: admin
      BITCOIN_RPCPASSWORD: strongpassword123
      BITCOIN_EXTRA_ARGS: |
        server=1
        txindex=1
        rpcallowip=0.0.0.0/0

volumes:
      - bitcoin-data:/bitcoin

# Downloads Zookeeper and Kafka images, sets up Zookeeper on port 2181, and Kafka on port 9092.
# Starts both containers with the necessary configurations.
# Also downloads Kafdrop for Kafka management and a Bitcoin node for blockchain interactions.
# tells the bitcoin node to use the testnet network with RPC enabled (allows Python scripts to interact with it).